on:
  push:
    branches:
      - main
    paths:
      - "*"
  pull_request:
    branches:
      - main
    paths:
      - "*"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |-
            |
            ${{ runner.os }}-node-modules-
      - name: Install dependencies
        run: npm install
      - name: Run tests (if exists)
        run: npm test || echo 'No test script found'
      - name: Restart nothing via PM2
        run: pm2 restart nothing || pm2 start npm --name "nothing" -- start
name: nothing Backend CI/CD
